server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 8.136.9.12:1111 # 换成linux中的nacos集群的地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
